version: 2.1

jobs:
  build:
    docker:
      - image: circleci/golang:1.16
    steps:
      - checkout
      - run:
          name: Build Golang Server
          command: cd server && go install -v -mod=vendor server/cmd/server
      - run:
          name: Test run
          command: cd server && ./bin/server
      - sonarcloud/scan

orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.1

workflows:
  main:
    jobs:
      - build:
          context: SonarCloud
